namespace DAX.IO.CIM
{

    public enum CIMClassEnum
    {
        Unknown = 0,
        ConnectivityNodeContainer = 1,
        Asset = 2,
        AssetOwner = 3,
        Maintainer = 4,
        CoordinateSystem = 5,
        Location = 6,
        PositionPoint = 7,
        UsagePoint = 8,
        BaseVoltage = 9,
        Bay = 10,
        GeographicalRegion = 12,
        Name = 13,
        NameType = 14,
        PSRType = 15,
        SubGeographicalRegion = 16,
        Substation = 17,
        Terminal = 18,
        VoltageLevel = 19,
        ACLineSegment = 20,
        ACLineSegmentExt = 21,
        AsynchronousMachine = 22,
        Breaker = 23,
        BusbarSection = 24,
        Disconnector = 25,
        EnergyConsumer = 26,
        ExternalNetworkInjection = 27,
        FaultIndicator = 28,
        FaultIndicatorExt = 29,
        Fuse = 30,
        Ground = 31,
        GroundDisconnector = 32,
        GroundingImpedance = 33,
        LinearShuntCompensator = 34,
        LoadBreakSwitch = 35,
        NonlinearShuntCompensator = 36,
        NonlinearShuntCompensatorPoint = 37,
        PetersenCoil = 38,
        PowerTransformer = 39,
        PowerTransformerEnd = 40,
        PowerTransformerEndExt = 41,
        RatioTapChanger = 42,
        ReactiveCapabilityCurve = 43,
        SeriesCompensator = 44,
        Switch = 45,
        SynchronousMachine = 46,
        TapSchedule = 47,
        CurrentTransformer = 48,
        CableInfo = 49,
        OverheadWireInfo = 50,
        SwitchInfo = 51,
        BusbarSectionInfo = 52,
        PotentialTransformer = 53,
        ProtectionEquipment = 54,
        Manufacturer = 55,
        ProductAssetModel = 56,

        // DAX Specific
        Enclosure = 100,
        BuildSimpleJunction = 101,
        TJunction = 102,
        ConnectivityNode = 201,
        ConnectivityEdge = 202,
        BuildNode = 500,
        EquipmentContainer = 1000,
        NetworkEquipment = 1001,
        LocationAddress = 1002,
        NetworkConnectionPoint = 1003
    }
}
