//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace DAX.CIM.Serialization.NetSam1_3.Measurement {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://net-sam.dk/measurement_1_0", IsNullable=false)]
    public partial class ProfileEnvelop {
        
        private Discrete[] discreteField;
        
        private DiscreteExt[] discreteExtField;
        
        private DiscreteValue[] discreteValueField;
        
        private MeasurementValueSource[] measurementValueSourceField;
        
        private UsagePoint[] usagePointField;
        
        private BaseVoltage[] baseVoltageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Discrete")]
        public Discrete[] Discrete {
            get {
                return this.discreteField;
            }
            set {
                this.discreteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiscreteExt")]
        public DiscreteExt[] DiscreteExt {
            get {
                return this.discreteExtField;
            }
            set {
                this.discreteExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiscreteValue")]
        public DiscreteValue[] DiscreteValue {
            get {
                return this.discreteValueField;
            }
            set {
                this.discreteValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MeasurementValueSource")]
        public MeasurementValueSource[] MeasurementValueSource {
            get {
                return this.measurementValueSourceField;
            }
            set {
                this.measurementValueSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsagePoint")]
        public UsagePoint[] UsagePoint {
            get {
                return this.usagePointField;
            }
            set {
                this.usagePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BaseVoltage")]
        public BaseVoltage[] BaseVoltage {
            get {
                return this.baseVoltageField;
            }
            set {
                this.baseVoltageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscreteExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class Discrete : Measurement {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Discrete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscreteExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public abstract partial class Measurement : IdentifiedObject {
        
        private string measurementTypeField;
        
        private MeasurementPowerSystemResource powerSystemResourceField;
        
        /// <remarks/>
        public string measurementType {
            get {
                return this.measurementTypeField;
            }
            set {
                this.measurementTypeField = value;
            }
        }
        
        /// <remarks/>
        public MeasurementPowerSystemResource PowerSystemResource {
            get {
                return this.powerSystemResourceField;
            }
            set {
                this.powerSystemResourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class MeasurementPowerSystemResource {
        
        private string referenceTypeField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class UsagePoint {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class Voltage {
        
        private UnitMultiplier multiplierField;
        
        private UnitSymbol unitField;
        
        private bool unitFieldSpecified;
        
        private float valueField;
        
        public Voltage() {
            this.unitField = UnitSymbol.V;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitMultiplier multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitSymbol unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public enum UnitMultiplier {
        
        /// <remarks/>
        c,
        
        /// <remarks/>
        d,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        k,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        micro,
        
        /// <remarks/>
        n,
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        p,
        
        /// <remarks/>
        T,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public enum UnitSymbol {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        deg,
        
        /// <remarks/>
        degC,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        g,
        
        /// <remarks/>
        h,
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        Hz,
        
        /// <remarks/>
        J,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        m2,
        
        /// <remarks/>
        m3,
        
        /// <remarks/>
        min,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        ohm,
        
        /// <remarks/>
        Pa,
        
        /// <remarks/>
        rad,
        
        /// <remarks/>
        s,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        VAh,
        
        /// <remarks/>
        VAr,
        
        /// <remarks/>
        VArh,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        Wh,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PowerSystemResource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseVoltage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasurementValueSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasurementValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscreteValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Measurement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Discrete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscreteExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public abstract partial class IdentifiedObject {
        
        private string mRIDField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public abstract partial class PowerSystemResource : IdentifiedObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class BaseVoltage : IdentifiedObject {
        
        private Voltage nominalVoltageField;
        
        /// <remarks/>
        public Voltage nominalVoltage {
            get {
                return this.nominalVoltageField;
            }
            set {
                this.nominalVoltageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class MeasurementValueSource : IdentifiedObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscreteValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public abstract partial class MeasurementValue : IdentifiedObject {
        
        private System.DateTime timeStampField;
        
        private bool timeStampFieldSpecified;
        
        private MeasurementValueMeasurementValueSource measurementValueSourceField;
        
        /// <remarks/>
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeStampSpecified {
            get {
                return this.timeStampFieldSpecified;
            }
            set {
                this.timeStampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MeasurementValueMeasurementValueSource MeasurementValueSource {
            get {
                return this.measurementValueSourceField;
            }
            set {
                this.measurementValueSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class MeasurementValueMeasurementValueSource {
        
        private string referenceTypeField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class DiscreteValue : MeasurementValue {
        
        private string valueField;
        
        private DiscreteValueDiscrete discreteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public DiscreteValueDiscrete Discrete {
            get {
                return this.discreteField;
            }
            set {
                this.discreteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class DiscreteValueDiscrete {
        
        private string referenceTypeField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class DiscreteExt : Discrete {
        
        private DiscreteExtUsagePoint usagePointField;
        
        /// <remarks/>
        public DiscreteExtUsagePoint UsagePoint {
            get {
                return this.usagePointField;
            }
            set {
                this.usagePointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://net-sam.dk/measurement_1_0")]
    public partial class DiscreteExtUsagePoint {
        
        private string referenceTypeField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
}
